# ============================================================
#   Progressive Skill Harness 环境配置脚本（PowerShell）
#   用法：在 PowerShell 中运行  .\setup_env.ps1
#   作用：安装依赖 + 引导输入 API Key + 验证环境
# ============================================================

$ErrorActionPreference = "Stop"
$projectRoot = $PSScriptRoot
Set-Location $projectRoot

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  Progressive Skill Harness — 环境配置向导" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  项目路径：$projectRoot"
Write-Host ""

# ---------- 1. 检查 Python ----------
Write-Host "[1/5] 检查 Python 环境..." -ForegroundColor Yellow
try {
    $pyVersion = python --version 2>&1
    Write-Host "  ✓ 已安装：$pyVersion" -ForegroundColor Green
} catch {
    Write-Host "  ✗ 未检测到 Python，请先安装 Python 3.10+" -ForegroundColor Red
    Write-Host "    下载地址：https://www.python.org/downloads/" -ForegroundColor Yellow
    exit 1
}

# ---------- 2. 创建虚拟环境 ----------
Write-Host ""
Write-Host "[2/5] 创建虚拟环境 .venv ..." -ForegroundColor Yellow
if (-Not (Test-Path ".venv")) {
    python -m venv .venv
    Write-Host "  ✓ 已创建 .venv" -ForegroundColor Green
} else {
    Write-Host "  · 已存在 .venv，跳过创建" -ForegroundColor Gray
}

# 激活虚拟环境
& .\.venv\Scripts\Activate.ps1
Write-Host "  ✓ 已激活虚拟环境" -ForegroundColor Green

# ---------- 3. 安装依赖 ----------
Write-Host ""
Write-Host "[3/5] 安装依赖包（首次需要 1~3 分钟）..." -ForegroundColor Yellow
$pipArgs = @(
    "--disable-pip-version-check",
    "install",
    "-r", "requirements.txt",
    "-i", "https://pypi.tuna.tsinghua.edu.cn/simple"
)
python -m pip @pipArgs
# pyyaml 是 workflow 类型 skill 必需
python -m pip install --disable-pip-version-check pyyaml -i https://pypi.tuna.tsinghua.edu.cn/simple | Out-Null
Write-Host "  ✓ 依赖安装完成（含 pyyaml）" -ForegroundColor Green

# ---------- 4. 配置 API Key ----------
Write-Host ""
Write-Host "[4/5] 配置 API Key..." -ForegroundColor Yellow
Write-Host ""
Write-Host "  请选择 LLM 提供商：" -ForegroundColor Cyan
Write-Host "    [1] DeepSeek（默认）"
Write-Host "    [2] Qwen (DashScope)"
$choice = Read-Host "  输入选项 (1/2，默认 1)"
if ([string]::IsNullOrWhiteSpace($choice)) { $choice = "1" }

$envPath = Join-Path $projectRoot ".env"

if ($choice -eq "1") {
    $provider = "deepseek"
    Write-Host ""
    Write-Host "  DeepSeek Key 获取：https://platform.deepseek.com/api_keys" -ForegroundColor Gray
    $dsKey = Read-Host "  请输入 DEEPSEEK_API_KEY"
    Write-Host "  DashScope Key（Embedding 必需，获取：https://dashscope.console.aliyun.com/apiKey）" -ForegroundColor Gray
    $qsKey = Read-Host "  请输入 DASHSCOPE_API_KEY"
} else {
    $provider = "qwen"
    Write-Host ""
    Write-Host "  DashScope Key 获取：https://dashscope.console.aliyun.com/apiKey" -ForegroundColor Gray
    $qsKey = Read-Host "  请输入 DASHSCOPE_API_KEY"
    $dsKey = $qsKey
}

@"
# Progressive Skill Harness - Environment Variables
# Generated by setup_env.ps1 at $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

LLM_PROVIDER=$provider
DEEPSEEK_API_KEY=$dsKey
DASHSCOPE_API_KEY=$qsKey
"@ | Out-File -FilePath $envPath -Encoding utf8

Write-Host "  ✓ 已写入 $envPath" -ForegroundColor Green

$env:LLM_PROVIDER = $provider
$env:DEEPSEEK_API_KEY = $dsKey
$env:DASHSCOPE_API_KEY = $qsKey

# ---------- 5. 验证环境 ----------
Write-Host ""
Write-Host "[5/5] 验证 Skill 注册表..." -ForegroundColor Yellow
python -c @"
import os, sys
sys.path.insert(0, 'src')
sys.path.insert(0, '.')
from skill_registry import get_registry
reg = get_registry()
summary = reg.summary()
print(f'  ✓ 已索引 {summary[\"skill_count\"]} 个 skill')
print(f'  ✓ 启动成本：{summary[\"frontmatter_total_chars\"]} 字符 frontmatter')
print(f'  ✓ 待按需加载正文：{summary[\"body_total_chars\"]} 字符')
for m in reg.items():
    print(f'    · {m.name} ({m.execution}) — {m.body_chars} 字符正文')
"@

Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  ✓ 环境配置完成" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  接下来你可以：" -ForegroundColor Cyan
Write-Host "    [A] 启动 CLI 版（终端对话）"
Write-Host "        python src/progressive_agent.py"
Write-Host ""
Write-Host "    [B] 启动 Web 版（浏览器访问 http://localhost:8000）"
Write-Host "        uvicorn src.progressive_serve:app --host 0.0.0.0 --port 8000"
Write-Host ""
Write-Host "  下次启动只需："
Write-Host "    cd '$projectRoot'"
Write-Host "    .\.venv\Scripts\Activate.ps1"
Write-Host "    # 重新加载 .env："
Write-Host "    Get-Content .env | ForEach-Object { if (`$_ -match '^([^=]+)=(.*)`$') { Set-Item -Path 'Env:\$(`$matches[1])' -Value `$matches[2] } }"
Write-Host ""